-- Usuario : Desarrollo
-- Pass : dev2019

-- USER SQL
CREATE USER DESARROLLO IDENTIFIED BY dev2019 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT LOCK;

-- QUOTAS
ALTER USER DESARROLLO QUOTA 300M ON USERS;

-- ROLES
GRANT "RESOURCE" TO DESARROLLO ;
GRANT "CONNECT"  TO DESARROLLO ;
