INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AF', 'Afganistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AL', 'Albania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'DE', 'Alemania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AD', 'Andorra');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AO', 'Angola');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AI', 'Anguila');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AG', 'Antigua y Barbuda');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AN', 'Antillas Neerlandesas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AQ', 'Antártida');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SA', 'Arabia Saudí');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'DZ', 'Argelia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AR', 'Argentina');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AM', 'Armenia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AW', 'Aruba');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AU', 'Australia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AT', 'Austria');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AZ', 'Azerbaiyán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BS', 'Bahamas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BH', 'Bahréin');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BD', 'Bangladesh');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BB', 'Barbados');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BZ', 'Belice');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BJ', 'Benín');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BM', 'Bermudas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BY', 'Bielorrusia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BO', 'Bolivia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BA', 'Bosnia-Herzegovina');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BW', 'Botsuana');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BR', 'Brasil');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BN', 'Brunéi');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BG', 'Bulgaria');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BF', 'Burkina Faso');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BI', 'Burundi');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BT', 'Bután');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BE', 'Bélgica');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CV', 'Cabo Verde');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KH', 'Camboya');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CM', 'Camerún');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CA', 'Canadá');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TD', 'Chad');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CL', 'Chile');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CN', 'China');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CY', 'Chipre');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VA', 'Ciudad del Vaticano');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CO', 'Colombia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KM', 'Comoras');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CG', 'Congo');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KP', 'Corea del Norte');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KR', 'Corea del Sur');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CR', 'Costa Rica');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CI', 'Costa de Marfil');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'HR', 'Croacia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CU', 'Cuba');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'DK', 'Dinamarca');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'DM', 'Dominica');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'EC', 'Ecuador');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'EG', 'Egipto');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SV', 'El Salvador');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AE', 'Emiratos Árabes Unidos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ER', 'Eritrea');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SK', 'Eslovaquia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SI', 'Eslovenia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ES', 'España');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'US', 'Estados Unidos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'EE', 'Estonia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ET', 'Etiopía');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PH', 'Filipinas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'FI', 'Finlandia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'FJ', 'Fiyi');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'FR', 'Francia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GA', 'Gabón');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GM', 'Gambia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GE', 'Georgia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GH', 'Ghana');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GI', 'Gibraltar');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GD', 'Granada');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GR', 'Grecia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GL', 'Groenlandia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GP', 'Guadalupe');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GU', 'Guam');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GT', 'Guatemala');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GF', 'Guayana Francesa');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GG', 'Guernsey');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GN', 'Guinea');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GQ', 'Guinea Ecuatorial');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GW', 'Guinea-Bissau');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GY', 'Guyana');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'HT', 'Haití');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'HN', 'Honduras');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'HU', 'Hungría');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IN', 'India');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ID', 'Indonesia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IQ', 'Iraq');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IE', 'Irlanda');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IR', 'Irán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BV', 'Isla Bouvet');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CX', 'Isla Christmas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NU', 'Isla Niue');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NF', 'Isla Norfolk');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IM', 'Isla de Man');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IS', 'Islandia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KY', 'Islas Caimán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CC', 'Islas Cocos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CK', 'Islas Cook');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'FO', 'Islas Feroe');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GS', 'Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'HM', 'Islas Heard y McDonald');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'FK', 'Islas Malvinas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MP', 'Islas Marianas del Norte');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MH', 'Islas Marshall');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SB', 'Islas Salomón');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TC', 'Islas Turcas y Caicos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VG', 'Islas Vírgenes Británicas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'UM', 'Islas menores alejadas de los Estados Unidos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AX', 'Islas Åland');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IL', 'Israel');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IT', 'Italia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'JM', 'Jamaica');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'JP', 'Japón');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'JE', 'Jersey');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'JO', 'Jordania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KZ', 'Kazajistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KE', 'Kenia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KG', 'Kirguistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KI', 'Kiribati');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KW', 'Kuwait');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LA', 'Laos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LS', 'Lesoto');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LV', 'Letonia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LR', 'Liberia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LY', 'Libia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LI', 'Liechtenstein');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LT', 'Lituania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LU', 'Luxemburgo');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LB', 'Líbano');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MK', 'Macedonia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MG', 'Madagascar');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MY', 'Malasia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MW', 'Malaui');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MV', 'Maldivas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ML', 'Mali');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MT', 'Malta');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MA', 'Marruecos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MQ', 'Martinica');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MU', 'Mauricio');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MR', 'Mauritania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'YT', 'Mayotte');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'FM', 'Micronesia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MD', 'Moldavia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MN', 'Mongolia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ME', 'Montenegro');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MS', 'Montserrat');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MZ', 'Mozambique');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MM', 'Myanmar');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MX', 'México');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MC', 'Mónaco');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NA', 'Namibia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NR', 'Nauru');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NP', 'Nepal');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NI', 'Nicaragua');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NG', 'Nigeria');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NO', 'Noruega');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NC', 'Nueva Caledonia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NZ', 'Nueva Zelanda');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NE', 'Níger');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'OM', 'Omán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PK', 'Pakistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PW', 'Palau');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PS', 'Palestina');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PA', 'Panamá');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PG', 'Papúa Nueva Guinea');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PY', 'Paraguay');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'NL', 'Países Bajos');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PE', 'Perú');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PN', 'Pitcairn');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PF', 'Polinesia Francesa');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PL', 'Polonia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PT', 'Portugal');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PR', 'Puerto Rico');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'QA', 'Qatar');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'HK', 'Región Administrativa Especial de Hong Kong de la República Popular China');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MO', 'Región Administrativa Especial de Macao de la República Popular China');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ZZ', 'Región desconocida o no válida');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'GB', 'Reino Unido');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CF', 'República Centroafricana');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CZ', 'República Checa');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CD', 'República Democrática del Congo');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'DO', 'República Dominicana');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'RE', 'Reunión');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'RW', 'Ruanda');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'RO', 'Rumanía');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'RU', 'Rusia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'WS', 'Samoa');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'AS', 'Samoa Americana');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'BL', 'San Bartolomé');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'KN', 'San Cristóbal y Nieves');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SM', 'San Marino');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'MF', 'San Martín');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'PM', 'San Pedro y Miquelón');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VC', 'San Vicente y las Granadinas');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SH', 'Santa Elena');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LC', 'Santa Lucía');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ST', 'Santo Tomé y Príncipe');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SN', 'Senegal');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'RS', 'Serbia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CS', 'Serbia y Montenegro');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SC', 'Seychelles');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SL', 'Sierra Leona');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SG', 'Singapur');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SY', 'Siria');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SO', 'Somalia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'LK', 'Sri Lanka');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SZ', 'Suazilandia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ZA', 'Sudáfrica');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SD', 'Sudán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SE', 'Suecia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'CH', 'Suiza');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SR', 'Surinam');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'SJ', 'Svalbard y Jan Mayen');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'EH', 'Sáhara Occidental');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TH', 'Tailandia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TW', 'Taiwán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TZ', 'Tanzania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TJ', 'Tayikistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'IO', 'Territorio Británico del Océano Índico');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TF', 'Territorios Australes Franceses');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TL', 'Timor Oriental');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TG', 'Togo');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TK', 'Tokelau');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TO', 'Tonga');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TT', 'Trinidad y Tobago');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TM', 'Turkmenistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TR', 'Turquía');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TV', 'Tuvalu');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'TN', 'Túnez');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'UA', 'Ucrania');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'UG', 'Uganda');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'UY', 'Uruguay');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'UZ', 'Uzbekistán');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VU', 'Vanuatu');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VE', 'Venezuela');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'VN', 'Vietnam');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'WF', 'Wallis y Futuna');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'YE', 'Yemen');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'DJ', 'Yibuti');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ZM', 'Zambia');
INSERT INTO pais(dtcreacion,lactivo, cclave, cnombre) VALUES (CURRENT_TIMESTAMP, 1,'ZW', 'Zimbabue');
