--Crear el secuenciador
CREATE SEQUENCE DESARROLLO.seq_id_alumno
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DESARROLLO.seq_id_materia
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DESARROLLO.seq_id_profesor
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE DESARROLLO.seq_id_bitacora
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE DESARROLLO.tbl_alumno (    
    iidalumno    INT NOT NULL, 
    snombre      VARCHAR2(128) NOT NULL,
    sprimerap    VARCHAR2(128) NOT NULL,
    ssegundoap   VARCHAR2(128) NOT NULL,
    dtfecha_nacimiento   date DEFAULT NULL,
    dtfecha_creacion     timestamp  DEFAULT CURRENT_TIMESTAMP,
    dtfecha_modificacion timestamp  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ALUMNO PRIMARY KEY (iidalumno)
);


CREATE TABLE DESARROLLO.tbl_materia (    
    iidmateria      INTEGER NOT NULL, 
    snombre         VARCHAR2(128) NOT NULL,
    sdescripcion    VARCHAR2(128) NOT NULL,    
    dtfecha_creacion     timestamp DEFAULT CURRENT_TIMESTAMP,
    dtfecha_modificacion timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MATERIA PRIMARY KEY (iidmateria)
);

CREATE TABLE DESARROLLO.tbl_profesor (    
    iidprofesor     INTEGER NOT NULL, 
    snombre         VARCHAR2(128) NOT NULL,
    sprimerap    VARCHAR2(128) NOT NULL,
    ssegundoap   VARCHAR2(128) NOT NULL,
    dtfecha_creacion     timestamp DEFAULT CURRENT_TIMESTAMP,
    dtfecha_modificacion timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PROFESOR PRIMARY KEY (iidprofesor)
);

CREATE TABLE DESARROLLO.tbl_bitacora (    
    iidbitacora     INTEGER NOT NULL, 
    sIPAddress 		VARCHAR2(128) NOT NULL,
	sUsuario 		VARCHAR2(128) NOT NULL,
    sEvento    		VARCHAR2(128) NOT NULL,
	sDatos    		VARCHAR2(1024),
    sComentario   	VARCHAR2(1024),
    dtfecha_creacion     timestamp DEFAULT CURRENT_TIMESTAMP,
    dtfecha_modificacion timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_Bitacora PRIMARY KEY (iidbitacora)
);

-- Insertar datos
INSERT INTO DESARROLLO.TBL_ALUMNO(IIDALUMNO, SNOMBRE, SPRIMERAP, SSEGUNDOAP, dtfecha_nacimiento, DTFECHA_CREACION, DTFECHA_MODIFICACION)
VALUES(DESARROLLO.seq_id_alumno.nextval, 'JUAN', 'PÉREZ', 'CAMPOS', TO_DATE('2001-03-01', 'YYYY-MM-DD'),CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DESARROLLO.TBL_ALUMNO(IIDALUMNO, SNOMBRE, SPRIMERAP, SSEGUNDOAP, dtfecha_nacimiento,DTFECHA_CREACION, DTFECHA_MODIFICACION)
VALUES(DESARROLLO.seq_id_alumno.nextval, 'Homero', 'Thompson', 'Thompson', TO_DATE('2002-02-01', 'YYYY-MM-DD'),CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DESARROLLO.TBL_ALUMNO(IIDALUMNO, SNOMBRE, SPRIMERAP, SSEGUNDOAP, dtfecha_nacimiento,DTFECHA_CREACION, DTFECHA_MODIFICACION)
VALUES(DESARROLLO.seq_id_alumno.nextval, 'PAULINA', 'CASTRO', 'LOPEZ', TO_DATE('2000-01-01', 'YYYY-MM-DD'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

commit;
