-- Usuario : AUDITORIA
-- Pass : audit2019

-- USER SQL
CREATE USER AUDITORIA IDENTIFIED BY audit2019 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER AUDITORIA QUOTA 600M ON USERS;

-- ROLES
GRANT CONNECT, RESOURCE, DBA TO AUDITORIA;

GRANT UNLIMITED TABLESPACE TO AUDITORIA;
