-- Usuario : PROGRAMADOR
-- Pass : prog2019

-- USER SQL
CREATE USER PROGRAMADOR IDENTIFIED BY prog2019 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER PROGRAMADOR QUOTA 600M ON USERS;

-- ROLES
GRANT CONNECT, RESOURCE TO PROGRAMADOR;

GRANT UNLIMITED TABLESPACE TO PROGRAMADOR;

-- Permiso para crear sinonimos
-- GRANT CREATE SYNONYM TO PROGRAMADOR;
GRANT CREATE SYNONYM, CREATE VIEW, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO PROGRAMADOR;